### ISSUE TITLE
adjust headers according to Zap reccommendations

### ISSUE THREAD

**Issue by joriscram** [OFBDABV/SBTi#113]
X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks.
This page contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception. This information can be used to launch further attacks against the web application. The alert could be a false positive if the error message is found inside a documentation page. This is linked to the internal server error message, which apperently discloses which kind of server we use
A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible. For the AWSALB and AWSALBCORS coockie
A cookie has been set without the SameSite attribute, which means that the cookie can be sent as a result of a 'cross-site' request. The SameSite attribute is an effective counter measure to cross-site request forgery, cross-site script inclusion, and timing attacks. for the same coockies
The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content. This can lead to functional errors
The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.

**Comment by ofjpostema** [comment]
* X-Frame-Options: Fixed
* Error/warning messages: Fixed for the API
* Cookies: This only happens in AWS, we don't set cookies ourselves. The deployment is up to the user, so it's their task to solve these issues
* cache-control and pragma HTTP headers: Fixed
* X-Content-Type-Options: Fixed
