### ISSUE TITLE
Map SBTi targets on ISIN instead of Company names

### ISSUE THREAD

**Issue by joriscram** [OFBDABV/SBTi#171]

**Comment by cschmidli** [comment]
I was just wondering, what is the reason to use ISIN as an attribute for the mapping? I understand it's most probably better than the company name, but isn't it up to the data provider/user to apply the id that fits their data structure? E.g. in the case of Bloomberg, they'd probably use their own id. If I remember correctly, there can be multiple ISINs for a given company depending on the type of security and market place.
