### ISSUE TITLE
Use FastAPI (instead of Flask) for API Server

### ISSUE THREAD

**Issue by cschmidli** [OFBDABV/SBTi#178]
Compared to Flask, [FastAPI](https://fastapi.tiangolo.com/) has the following benefits:
- DTOs/models can be based on python's type hints
- swagger docs are generated from the code based on the types/models (no manual
- validations of the payload can easily be validated too
- its default implementation is very fast 

Additionally:
- it's very easy to extend and has great documentation
- the library is well support at the moment

check out the [FastAPI page](https://fastapi.tiangolo.com/) for more details

Since the API server is still fairly small and in development, this probably shouldn't take too long

**Comment by joriscram** [comment]
also solves that the /dataproviders end-point is not included in swagger currently

**Comment by cschmidli** [comment]
already started on this one? anything I can help out with? :)
