### ISSUE TITLE
Update SBTi companies taking action file

### ISSUE THREAD

**Issue by DaanvdMeeberg** [OFBDABV/SBTi#209]
- sbti regularly updates it's list of companies with approved targets, somehow we need to be able to update this list in the tool.
**explicit action in the API (update SBTi file)?
**Implicit: check this every time you run the tool?
**Manually update GitHub solution (sbti action)?
**Direct connection to sbti database (if sbti updated website)

- optional to use the data provider as source of SBTi approved companies

**Comment by joriscram** [comment]
Ortec Finance will commit new versions to GitHub
